//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DA
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class LearnEntities1 : DbContext
    {
        public LearnEntities1()
            : base("name=LearnEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<dept> depts { get; set; }
        public virtual DbSet<emp> emps { get; set; }
    
        public virtual int inserting(string name, string adress, Nullable<int> did)
        {
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var adressParameter = adress != null ?
                new ObjectParameter("adress", adress) :
                new ObjectParameter("adress", typeof(string));
    
            var didParameter = did.HasValue ?
                new ObjectParameter("did", did) :
                new ObjectParameter("did", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("inserting", nameParameter, adressParameter, didParameter);
        }
    
        public virtual ObjectResult<mmd_Result> mmd(Nullable<int> idd)
        {
            var iddParameter = idd.HasValue ?
                new ObjectParameter("idd", idd) :
                new ObjectParameter("idd", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<mmd_Result>("mmd", iddParameter);
        }
    }
}
